// user-card/index.jsx
import { useEffect, useState } from "react";
import { Card, Descriptions, Avatar, List } from "antd";
import { UserOutlined } from "@ant-design/icons";
import "antd/dist/reset.css"; // 全局引入 AntD 样式

// 内部 React 组件
export default function UserCard({ name, age,listData = [] }) {
  const [height, setHeight] = useState(260);

  useEffect(() => {
    const interval = setInterval(() => {
      setHeight((prev) => prev + 10); // 每秒增加高度10px
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <Card
      style={{
        width: 260,
        height: height,
        borderRadius: 16,
        boxShadow: "0 8px 20px rgba(0,0,0,0.15)",
        transition: "height 0.5s ease",
        background: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
        overflow: "hidden",
      }}
    >
      <div style={{ textAlign: "center", marginBottom: 16 }}>
        <Avatar size={64} icon={<UserOutlined />} />
        <h3 style={{ marginTop: 12, color: "#fff" }}>{name}</h3>
      </div>

      <Descriptions
        size="small"
        column={1}
        bordered
        style={{
          background: "rgba(255,255,255,0.2)",
          borderRadius: 8,
        }}
      >
        <Descriptions.Item label="Name" style={{ color: "#fff" }}>
          {name}
        </Descriptions.Item>
        <Descriptions.Item label="Age" style={{ color: "#fff" }}>
          {age}
        </Descriptions.Item>
      </Descriptions>

      <List
        itemLayout="horizontal"
        dataSource={listData}
        renderItem={(item) => (
          <List.Item>
            <List.Item.Meta
              avatar={<Avatar icon={<UserOutlined />} />}
              title={<a href="https://ant.design">{item.title}</a>}
              description="Ant Design, a design language for background applications, is refined by Ant UED Team"
            />
          </List.Item>
        )}
      />
    </Card>
  );
}

// user-card-vue/src/components/UserCard.vue
<template>
  <el-card
    :style="{
      width: '260px',
      height: height + 'px',
      borderRadius: '16px',
      boxShadow: '0 8px 20px rgba(0,0,0,0.15)',
      transition: 'height 0.5s ease',
      background: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
      overflow: 'hidden'
    }"
  >
    <div style="text-align:center; margin-bottom: 16px;">
      <el-avatar :size="64" icon="User" />
      <h3 style="margin-top: 12px; color: #fff;">{{ name }}</h3>
    </div>

    <el-descriptions
      :column="1"
      size="small"
      style="background: rgba(255,255,255,0.2); border-radius: 8px;"
    >
      <el-descriptions-item label="Name">
        <span style="color:#fff">{{ name }}</span>
      </el-descriptions-item>

      <el-descriptions-item label="Age">
        <span style="color:#fff">{{ age }}</span>
      </el-descriptions-item>
    </el-descriptions>

    <div style="margin-top: 16px;">
      <div
        v-for="item in listData"
        :key="item.title"
        style="display:flex; align-items:center; padding: 8px 0;"
      >
        <el-avatar icon="User" style="margin-right: 8px;" />
        <div>
          <a href="https://element-plus.org">{{ item.title }}</a>
          <div style="font-size: 12px; opacity: 0.7;">
            Element Plus example description...
          </div>
        </div>
      </div>
    </div>
  </el-card>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";

const props = defineProps({
  name: { type: String, default: "unknown" },
  age: { type: [String, Number], default: 0 },
  listData: { type: Array, default: () => [] }
});

const height = ref(260);
let timer = null;

onMounted(() => {
  timer = setInterval(() => {
    height.value += 10;
  }, 1000);
});

onBeforeUnmount(() => {
  if (timer) clearInterval(timer);
});
</script>
